openapi: 3.1.1
info:
  title: サブスク管理アプリ API
  description: |
    サブスクリプションサービス管理アプリケーションのAPI仕様書です。
    ユーザー認証、サブスクリプション管理、支払い履歴、各種設定など
    アプリの全機能をREST APIで利用することができます。
  version: 1.0.0
  contact:
    name: SubsTracker Support
    email: support@substracker.example.com

servers:
  - url: https://api.substracker.example.com/api/v1
    description: 本番環境
  - url: https://staging-api.substracker.example.com/api/v1
    description: ステージング環境
  - url: http://localhost:5000/api/v1
    description: 開発環境

tags:
  - name: 認証
    description: ユーザー認証関連のAPI
  - name: サブスクリプション
    description: サブスクリプション管理関連のAPI
  - name: 支払い履歴
    description: 支払い履歴管理関連のAPI
  - name: プロフィール設定
    description: ユーザープロフィール設定関連のAPI
  - name: 通貨設定
    description: 通貨・為替レート設定関連のAPI
  - name: 支払い方法設定
    description: 支払い方法設定関連のAPI
  - name: 通知設定
    description: 通知設定関連のAPI
  - name: ラベル管理
    description: ラベル管理関連のAPI
  - name: マスターデータ
    description: マスターデータ関連のAPI

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'JWTトークンをヘッダーに付与してください: `Authorization: Bearer {token}`'

  schemas:
    # 共通のスキーマ
    Meta:
      type: object
      properties:
        pagination:
          type: object
          properties:
            current_page:
              type: integer
              description: 現在のページ
            total_pages:
              type: integer
              description: 総ページ数
            total_items:
              type: integer
              description: 総アイテム数
            per_page:
              type: integer
              description: 1ページあたりの件数
          required:
            - current_page
            - total_pages
            - total_items
            - per_page
        summary:
          type: object
          properties:
            total_amount:
              type: number
              description: 合計金額

    # エラー関連のスキーマ
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              description: エラーコード
            message:
              type: string
              description: エラーメッセージ
            details:
              type: object
              description: 詳細情報
          required:
            - code
            - message

  responses:
    BadRequest:
      description: リクエストが不正です
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            validation_error:
              value:
                error:
                  code: VALIDATION_REQUIRED
                  message: 必須項目が入力されていません
                  details:
                    field: name
                    reason: 必須項目です

    Unauthorized:
      description: 認証に失敗しました
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            invalid_token:
              value:
                error:
                  code: AUTH_INVALID_TOKEN
                  message: 無効なトークンです

    Forbidden:
      description: 権限がありません
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            unauthorized:
              value:
                error:
                  code: AUTH_UNAUTHORIZED
                  message: この操作を行う権限がありません

    NotFound:
      description: リソースが見つかりません
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            resource_not_found:
              value:
                error:
                  code: RESOURCE_NOT_FOUND
                  message: 指定されたリソースが見つかりません
