steps:
  # ステップ1: 本番イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'docker/Dockerfile'
      - '--target=production'
      - '-t'
      # イメージ名 「リージョン-docker.pkg.dev/プロジェクトID/リポジトリ名/イメージ名:タグ」
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '.'

  # ステップ2: ビルドしたイメージをArtifact Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'

  # ステップ3: 新しいイメージを使ってCloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--min-instances=1'
      - '--allow-unauthenticated'
      # Secret Managerから秘密鍵を環境変数としてセットする
      - '--set-secrets=JWT_SECRET_KEY=JWT_SECRET_KEY:latest'

# ビルドしたイメージを保存しておく設定
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
