services:
  backend-api:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
      target: builder
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/workspace:cached
      - poetry-cache:/tmp/poetry_cache
    command: poetry run flask --app 'app:create_app()' run --host=0.0.0.0 --debug

volumes:
  poetry-cache:
