services:
  backend-api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: production
    ports:
      - "8080:8080" # Cloud Runのデフォルトに合わせる
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
