exclude = [
    ".venv",
    "venv",
    "__pycache__",
    ".git",
]

line-length = 100
indent-width = 4

[lint]
select = [
    "ALL"
]
ignore = ["D200", "D212", "D400", "D401", "D413", "D415", "E402", "FA102", "RUF002"]
fixable = ["ALL"]


[format]
quote-style = "double"

[lint.mccabe]
# if,forなどの複雑性をどれくらい許容するか。if,for文が11以上あると警告
# C901
max-complexity = 10

# tests配下は、部分的にルールを無効化: ex. マジックナンバー、assert
[per-file-ignores]
"tests/**/*.py" = [
    "INP001",  # Implicit namespace package
    "ANN201",  # Missing return type annotation for public function
    "ANN202",  # Missing return type annotation for public function
    "D100", "D413",
    "D103",    # Disable public test function docstring
    "S101",    # Use of assert detected
    "S105", "S106", "S107",    # Permit of hard-coded password
    "PLR2004", # Magic value used in comparison
    "FA100",   # Disable type hinting of Optional, Union, etc.
    "SLF001",  # Disable private function annotation
]
