exclude = [
    ".venv",
    "venv",
    "__pycache__",
    ".git",
]

line-length = 100
indent-width = 4

[lint]
select = [
    "ALL"
]
ignore = ["D200", "D212", "D400", "D415", "E402", "FA102"]
fixable = ["ALL"]


[format]
quote-style = "double"

[lint.mccabe]
# if,forなどの複雑性をどれくらい許容するか。if,for文が11以上あると警告
# C901
max-complexity = 10
