"""add_base_currency_to_user

Revision ID: 36e602ae28aa
Revises: 6c1f3eb59006
Create Date: 2025-11-24 02:13:58.499226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e602ae28aa'
down_revision: Union[str, None] = '6c1f3eb59006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_litestream_seq')
    op.drop_table('_litestream_lock')
    op.add_column('users', sa.Column('base_currency', sa.String(length=3), server_default='USD', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'base_currency')
    op.create_table('_litestream_lock',
    sa.Column('id', sa.INTEGER(), nullable=True)
    )
    op.create_table('_litestream_seq',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('seq', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
