"""Make next_payment_date nullable and indexed in Subscription

Revision ID: 45a83c3bd8b1
Revises: d310093f612e
Create Date: 2025-11-03 12:09:47.726790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a83c3bd8b1'
down_revision: Union[str, None] = 'd310093f612e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('next_payment_date',
                   existing_type=sa.DATE(),
                   nullable=True)
        batch_op.create_index(batch_op.f('ix_subscriptions_next_payment_date'), ['next_payment_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_next_payment_date'))
        batch_op.alter_column('next_payment_date',
                   existing_type=sa.DATE(),
                   nullable=False)
    # ### end Alembic commands ###
