"""Create payment_histories table

Revision ID: 5e49d7c53018
Revises: c8f3995f5449
Create Date: 2025-11-03 02:49:01.232472

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e49d7c53018"
down_revision: Union[str, None] = "c8f3995f5449"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_histories",
        sa.Column("payment_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=True),
        sa.Column("subscription_name", sa.String(length=100), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.REAL(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rate_from_currency", sa.String(length=3), nullable=False),
        sa.Column("rate_to_currency", sa.String(length=3), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("payment_method", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rate_from_currency", "rate_to_currency", "rate_date"],
            [
                "exchange_rates.from_currency",
                "exchange_rates.to_currency",
                "exchange_rates.date",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.subscription_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("payment_id"),
    )
    op.create_index(
        op.f("ix_payment_histories_subscription_id"),
        "payment_histories",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_histories_user_id"),
        "payment_histories",
        ["user_id"],
        unique=False,
    )
    op.execute("DROP TABLE IF EXISTS _litestream_seq")
    op.execute("DROP TABLE IF EXISTS _litestream_lock")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("_litestream_lock", sa.Column("id", sa.INTEGER(), nullable=True))
    op.create_table(
        "_litestream_seq",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("seq", sa.INTEGER(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("ix_payment_histories_user_id"), table_name="payment_histories")
    op.drop_index(
        op.f("ix_payment_histories_subscription_id"), table_name="payment_histories"
    )
    op.drop_table("payment_histories")
    # ### end Alembic commands ###
