"""add exchange_rate and converted_amount to payment_history

Revision ID: 6c1f3eb59006
Revises: 45a83c3bd8b1
Create Date: 2025-11-23 12:46:07.576182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1f3eb59006'
down_revision: Union[str, None] = '45a83c3bd8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_litestream_seq')
    op.drop_table('_litestream_lock')
    op.add_column('payment_histories', sa.Column('exchange_rate', sa.REAL(), nullable=True))
    op.add_column('payment_histories', sa.Column('converted_amount', sa.REAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_histories', 'converted_amount')
    op.drop_column('payment_histories', 'exchange_rate')
    op.create_table('_litestream_lock',
    sa.Column('id', sa.INTEGER(), nullable=True)
    )
    op.create_table('_litestream_seq',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('seq', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
