"""create_payment_histories_table

Revision ID: d310093f612e
Revises: 5e49d7c53018
Create Date: 2025-11-03 07:47:50.939957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d310093f612e"
down_revision: Union[str, None] = "5e49d7c53018"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS _litestream_seq")
    op.execute("DROP TABLE IF EXISTS _litestream_lock")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("_litestream_lock", sa.Column("id", sa.INTEGER(), nullable=True))
    op.create_table(
        "_litestream_seq",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("seq", sa.INTEGER(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
